#application name
spring.application.name=zombie-cleaner-server

#database
spring.datasource.url = ${DATABASE_URL}
spring.datasource.username = ${DATABASE_USERNAME}
spring.datasource.password = ${DATABASE_PASSWORD}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

#AWS credentials
aws.assume-role.role-arn = ${ROLE_ARN}
aws.assume-role.session-name = ${SESSION_NAME}
aws.region = ${REGION}

#security and auth
auth.security.secret.key = ${SECURITY_KEY}
auth.security.expiration.hours = ${EXPIRATION_HOURS}

#routing
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

#hybernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Enable debug logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# application-dev.properties
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1500ms
spring.devtools.restart.quiet-period=1000ms

# Exclude certain paths from triggering restart
spring.devtools.restart.exclude=static/**,public/**,templates/**

# Additional restart trigger locations
spring.devtools.restart.additional-paths=src/main/java